[window]
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 10
y = 10

decorations = "full"

[font]
normal.family = "Fira Code"
normal.style = "Regular"
bold.family = "Fira Code"
bold.style = "Bold"
italic.family = "Fira Code"
italic.style = "Italic"

size = 12.0

[offset]
x = 0
y = 0

[glyph_offset]
x = 0
y = 0

[colors]
primary.background = "#282c34"
primary.foreground = "#abb2bf"

[colors.normal]
black = "#1c1e26"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#dfdfdf"

[colors.bright]
black = "#4b5263"
red = "#be5046"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#ffffff"

background_opacity = 0.9

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = "Block"
color = "#528b8b"

[key_bindings]
[[key_bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[key_bindings]]
key = "Q"
mods = "Control"
action = "Quit"

[shell]
program = "/usr/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"
LANG = "en_US.UTF-8"

[performance]
swap_redraws = true
vsync = true

[dpi]
x = 1.0
y = 1.0

